name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * 0" # Every Sunday at 6:15 UTC
  workflow_dispatch: # Manually triggered

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get event name
        run: echo "Event: ${{ github.event_name }}"

      - name: Get current branch name
        run: echo "Current branch: ${{ github.ref }}"

      - name: List all files
        run: |
          find . -type f